/**
 * conscription_cron.ts — The cron that turns student observations into shipped code patches.
 *
 * Reads witness-logs from a Quilt cell-graph JSON dump, tallies feature_request observations,
 * and ships patches for features with consensus ≥ 5%.
 *
 * Usage: 
 *   npx tsx /workspace/research/cargo-line-tycoon/cron/conscription_cron.ts <witness_log.json>
 *   npx tsx /workspace/research/cargo-line-tycoon/cron/conscription_cron.ts --test
 */

import * as fs from 'fs';
import * as path from 'path';

interface WitnessEntry {
  op: string;
  source: string;
  payload: any;
  timestamp: number;
}

interface StudentSignal {
  source: string;
  target: string;
  signal_type: string;
  payload: any;
  timestamp: number;
}

interface PatchDecision {
  feature: string;
  consensus_pct: number;
  supporters: string[];
  patch_path: string;
  shipped_at: number;
}

interface RunLog {
  timestamp: number;
  witness_log_file: string;
  n_students: number;
  n_observations: number;
  n_features_requested: number;
  top_features: Array<{ feature: string; votes: number; pct: number }>;
  patches_shipped: PatchDecision[];
  consensus_threshold: number;
  total_features_in_canon: number;
}

const CONSENSUS_THRESHOLD = 0.05;  // 5%

function loadWitnessLog(file: string): { students: Set<string>; signals: StudentSignal[] } {
  const raw = JSON.parse(fs.readFileSync(file, 'utf-8'));
  const signals = raw.signals || [];
  const students = new Set<string>();
  for (const sig of signals) {
    if (sig.signal_type === 'feature_request' && sig.payload?.requested_by) {
      students.add(sig.payload.requested_by);
    }
  }
  return { students, signals };
}

function tallyFeatureRequests(signals: StudentSignal[]): Map<string, string[]> {
  const tallies = new Map<string, string[]>();
  for (const sig of signals) {
    if (sig.signal_type === 'feature_request' && sig.payload?.feature) {
      const feature = sig.payload.feature;
      const requester = sig.payload.requested_by || sig.source;
      if (!tallies.has(feature)) tallies.set(feature, []);
      const supporters = tallies.get(feature)!;
      if (!supporters.includes(requester)) {
        supporters.push(requester);
      }
    }
  }
  return tallies;
}

function generatePatch(feature: string, supporter_count: number): string {
  const featureSafe = feature.replace(/[^a-z0-9_]/g, '_');
  const patchPath = path.join('/tmp', `patch_${featureSafe}.ts`);
  
  const patchContent = `// AUTO-GENERATED by conscription_cron.ts
// Feature: ${feature}
// Shipped at: ${new Date().toISOString()}
// Supporters: ${supporter_count}

export const feature_${featureSafe} = {
  name: '${feature}',
  shipped_at: Date.now(),
  shipped_by: 'conscription_cron',
  supporter_count: ${supporter_count},
  metadata: {
    auto_generated: true,
    feature_id: '${featureSafe}',
    source: 'witness-log quorum',
  },
};

export function activate_${featureSafe}() {
  return feature_${featureSafe};
}
`;

  fs.writeFileSync(patchPath, patchContent);
  return patchPath;
}

function runConscriptionCron(witnessLogFile: string): RunLog {
  console.log('╔════════════════════════════════════════════════════════════════╗');
  console.log('║  Conscription Cron — witness-log → code patches                ║');
  console.log('╚════════════════════════════════════════════════════════════════╝');
  console.log(`Witness log: ${witnessLogFile}`);
  console.log(`Consensus threshold: ${CONSENSUS_THRESHOLD * 100}%\n`);

  // 1. Load witness log
  const { students, signals } = loadWitnessLog(witnessLogFile);
  const n_students = students.size;
  const n_observations = signals.length;
  console.log(`Students: ${n_students}`);
  console.log(`Observations: ${n_observations}`);

  // 2. Tally feature requests
  const tallies = tallyFeatureRequests(signals);
  const features_requested = tallies.size;
  console.log(`Distinct features: ${features_requested}\n`);

  // 3. Sort by votes
  const ranked = Array.from(tallies.entries())
    .map(([feature, supporters]) => ({
      feature,
      votes: supporters.length,
      pct: supporters.length / Math.max(n_students, 1),
    }))
    .sort((a, b) => b.votes - a.votes);

  console.log('Top features by vote:');
  for (const r of ranked.slice(0, 10)) {
    const verdict = r.pct >= CONSENSUS_THRESHOLD ? '✓ PROMOTE' : '○ review';
    console.log(`  ${verdict}  ${r.feature.padEnd(28)} ${r.votes} votes (${(r.pct * 100).toFixed(1)}%)`);
  }
  console.log('');

  // 4. Ship patches for promoted features
  const patches: PatchDecision[] = [];
  const promoted = ranked.filter(r => r.pct >= CONSENSUS_THRESHOLD);
  
  for (const p of promoted) {
    const supporters = tallies.get(p.feature) || [];
    const patchPath = generatePatch(p.feature, supporters.length);
    patches.push({
      feature: p.feature,
      consensus_pct: p.pct,
      supporters,
      patch_path: patchPath,
      shipped_at: Date.now(),
    });
    console.log(`  → shipped: ${p.feature} (${patchPath})`);
  }

  // 5. Build run log
  const runLog: RunLog = {
    timestamp: Date.now(),
    witness_log_file: witnessLogFile,
    n_students,
    n_observations,
    n_features_requested: features_requested,
    top_features: ranked.slice(0, 20),
    patches_shipped: patches,
    consensus_threshold: CONSENSUS_THRESHOLD,
    total_features_in_canon: 0, // computed in JS port
  };
  
  console.log(`\nShipped: ${patches.length} patches`);
  return runLog;
}

// ─────────────────────────────────────────────────────────────────
// Test fixtures
// ─────────────────────────────────────────────────────────────────

function generateTestWitnessLog(students: number, features: number, density: number = 0.3): string {
  const FEATURES = [
    'weather_routing', 'fuel_estimator', 'crew_schedule', 'cargo_tier_picker',
    'speed_optimization', 'route_alternatives', 'piracy_zone_map', 'currency_converter',
    'time_zone_display', 'language_selector', 'sound_effects', 'background_music',
  ];
  const signals: StudentSignal[] = [];
  for (let i = 0; i < students; i++) {
    // Each student requests 1-3 features
    const nFeatures = 1 + Math.floor(Math.random() * 3);
    for (let j = 0; j < nFeatures; j++) {
      const f = FEATURES[Math.floor(Math.random() * Math.min(features, FEATURES.length))];
      if (Math.random() < density) {
        signals.push({
          source: `student_${i}`,
          target: 'coder_agent',
          signal_type: 'feature_request',
          payload: {
            requested_by: `student_${i}`,
            feature: f,
            tier: 1 + Math.floor(Math.random() * 3),
          },
          timestamp: Date.now(),
        });
      }
    }
  }
  return JSON.stringify({ signals });
}

function runTests(): void {
  console.log('═══ Conscription Cron — Test Suite ═══\n');

  // Test 1: Empty witness log
  console.log('Test 1: Empty witness log');
  const emptyFile = '/tmp/test_empty_witness.json';
  fs.writeFileSync(emptyFile, JSON.stringify({ signals: [] }));
  const r1 = runConscriptionCron(emptyFile);
  if (r1.patches_shipped.length !== 0) {
    console.log('  ✗ FAIL: should ship 0 patches on empty log');
    process.exit(1);
  }
  console.log('  ✓ 0 patches on empty log\n');

  // Test 2: 10 students, 1 feature each — top 50%
  console.log('Test 2: 10 students, 1 feature each (sparse)');
  const sparseLog = {
    signals: Array.from({ length: 10 }, (_, i) => ({
      source: `student_${i}`,
      target: 'coder_agent',
      signal_type: 'feature_request',
      payload: { requested_by: `student_${i}`, feature: 'weather_routing', tier: 1 },
      timestamp: Date.now(),
    }))
  };
  const sparseFile = '/tmp/test_sparse_witness.json';
  fs.writeFileSync(sparseFile, JSON.stringify(sparseLog));
  const r2 = runConscriptionCron(sparseFile);
  if (r2.patches_shipped.length !== 1) {
    console.log(`  ✗ FAIL: should ship 1 patch, got ${r2.patches_shipped.length}`);
    process.exit(1);
  }
  console.log(`  ✓ Shipped ${r2.patches_shipped.length} patch from sparse log\n`);

  // Test 3: 100 students, 50 distinct features (5% quorum)
  console.log('Test 3: 100 students, 50 features (consortium)');
  const denseLog = generateTestWitnessLog(100, 12, 1.0);
  const denseFile = '/tmp/test_dense_witness.json';
  fs.writeFileSync(denseFile, denseLog);
  const r3 = runConscriptionCron(denseFile);
  if (r3.patches_shipped.length === 0) {
    console.log('  ✗ FAIL: should ship some patches from dense log');
    process.exit(1);
  }
  console.log(`  ✓ Shipped ${r3.patches_shipped.length} patches from dense log\n`);

  // Test 4: Idempotency — running twice produces same patches
  console.log('Test 4: Idempotency (run twice, same result)');
  const r4a = runConscriptionCron(denseFile);
  const r4b = runConscriptionCron(denseFile);
  const featuresA = r4a.patches_shipped.map(p => p.feature).sort();
  const featuresB = r4b.patches_shipped.map(p => p.feature).sort();
  if (JSON.stringify(featuresA) !== JSON.stringify(featuresB)) {
    console.log('  ✗ FAIL: idempotency broken');
    console.log('  Run A:', featuresA);
    console.log('  Run B:', featuresB);
    process.exit(1);
  }
  console.log(`  ✓ Idempotent — both runs shipped same ${featuresA.length} features\n`);

  // Test 5: Conflicting votes — only majority ships
  console.log('Test 5: Conflicting votes — only majority ships');
  const conflictLog = {
    signals: [
      // 8 vote yes, 2 vote no
      ...Array.from({ length: 8 }, (_, i) => ({
        source: `student_${i}`, target: 'coder_agent', signal_type: 'feature_request',
        payload: { requested_by: `student_${i}`, feature: 'maj_feature', tier: 1 },
        timestamp: Date.now(),
      })),
      ...Array.from({ length: 2 }, (_, i) => ({
        source: `student_${10+i}`, target: 'coder_agent', signal_type: 'contest',
        payload: { requested_by: `student_${10+i}`, target_feature: 'maj_feature', vote: 'no' },
        timestamp: Date.now(),
      })),
    ]
  };
  const conflictFile = '/tmp/test_conflict_witness.json';
  fs.writeFileSync(conflictFile, JSON.stringify(conflictLog));
  const r5 = runConscriptionCron(conflictFile);
  // 8/10 = 80% > 5% so maj_feature should ship
  if (r5.patches_shipped.length === 0) {
    console.log('  ✗ FAIL: should ship maj_feature');
    process.exit(1);
  }
  console.log(`  ✓ Shipped ${r5.patches_shipped[0].feature} despite 2/10 contest votes\n`);

  console.log('═══════════════════════════════════════════════════════════════════');
  console.log('  ✓ All 5 tests PASS');
  console.log('═══════════════════════════════════════════════════════════════════');
  
  // Write run log
  const runLogPath = path.join('/workspace/research/cargo-line-tycoon/cron/runs', `run_${Date.now()}.json`);
  fs.mkdirSync(path.dirname(runLogPath), { recursive: true });
  fs.writeFileSync(runLogPath, JSON.stringify(r3, null, 2));
  console.log(`\nRun log saved to: ${runLogPath}`);
}

// ─────────────────────────────────────────────────────────────────
// Main
// ─────────────────────────────────────────────────────────────────

const args = process.argv.slice(2);

if (args.length === 0 || args[0] === '--help' || args[0] === '-h') {
  console.log('Usage:');
  console.log('  npx tsx conscription_cron.ts <witness_log.json>');
  console.log('  npx tsx conscription_cron.ts --test');
  process.exit(0);
}

if (args[0] === '--test') {
  runTests();
} else {
  const witnessLogFile = args[0];
  if (!fs.existsSync(witnessLogFile)) {
    console.error(`Witness log file not found: ${witnessLogFile}`);
    process.exit(1);
  }
  const runLog = runConscriptionCron(witnessLogFile);
  const runLogPath = path.join('/workspace/research/cargo-line-tycoon/cron/runs', `run_${Date.now()}.json`);
  fs.mkdirSync(path.dirname(runLogPath), { recursive: true });
  fs.writeFileSync(runLogPath, JSON.stringify(runLog, null, 2));
  console.log(`\nRun log saved to: ${runLogPath}`);
}

// ─────────────────────────────────────────────────────────────────
// Cron binding comment:
// 
// To deploy this as a Cloudflare Worker cron, add to wrangler.toml:
// 
//   [triggers]
//   crons = ["0 * * * *"]  # every hour
// 
// And convert this script to use the Cloudflare Workers runtime.
// The cron worker would:
//   1. Read witness-log from KV (canon_v3_neighbor file as a stand-in)
//   2. Run tallyFeatureRequests in-Worker
//   3. Write patches to a CF Pages project via the API
// ─────────────────────────────────────────────────────────────────
